[chttpd]
# Ensure you keep the default cookie and default handlers or you'll lock yourself out
authentication_handlers = {chttpd_auth, proxy_authentication_handler}, {chttpd_auth, cookie_authentication_handler}, {chttpd_auth, default_authentication_handler}

[couch_httpd_auth]
# IMPORTANT: This section must be [couch_httpd_auth], not [chttpd_auth]
proxy_use_secret = true
secret = SET_ME_PLEASE

[httpd]
enable_cors = true

[cors]
origins = *
credentials = true
methods = GET, POST, PUT, DELETE, OPTIONS